Models/ErrorViewModel.cs
namespace ToDoApplication_MVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/TodoItem.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace ToDoApplication_MVC.Models
{
    public class TodoItem
    {
        [Key]
        public int Id { get; set; }

        [Required]
        public string Name { get; set; }

        [Required]
        public string Description { get; set; }

        [Required]
        [DisplayName("Date and Time")]
        public DateTime DateAndTime { get; set; }

        [Required]
        public string Priority { get; set; }

        [Required]
        [DisplayName("Done")]
        public bool isDone { get; set; }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using ToDoApplication_MVC.Models;

namespace ToDoApplication_MVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/TodoItemController.cs
using Microsoft.AspNetCore.Mvc;
using ToDoApplication_MVC.Data;
using ToDoApplication_MVC.Models;

namespace ToDoApplication_MVC.Controllers
{
    public class TodoItemController : Controller
    {
        private readonly ApplicationDbContext _db;

        public TodoItemController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            IEnumerable<TodoItem> objTodoItemList = _db.TodoItems;

            return View(objTodoItemList);
        }

        //GET
        public IActionResult Create()
        {
            return View();
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(TodoItem obj)
        {
            if (obj.Priority == "")
            {
                ModelState.AddModelError("Priority", "The Priority is required.");
            }

            if (ModelState.IsValid)
            {
                _db.TodoItems.Add(obj);
                _db.SaveChanges();
                TempData["success"] = "New Task added successfully!";
                return RedirectToAction("Index");
            }

            return View(obj);
        }

        //GET
        public IActionResult Update(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var categoryFromDb = _db.TodoItems.Find(id);

            if (categoryFromDb == null)
            {
                return NotFound();
            }

            return View(categoryFromDb);
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update(TodoItem obj)
        {
            if (obj.Priority == "")
            {
                ModelState.AddModelError("Priority", "The Priority is required.");
            }

            if (ModelState.IsValid)
            {
                _db.TodoItems.Update(obj);
                _db.SaveChanges();
                TempData["success"] = "Task updated successfully!";
                return RedirectToAction("Index");
            }

            return View(obj);
        }

        //GET
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var categoryFromDb = _db.TodoItems.Find(id);

            if (categoryFromDb == null)
            {
                return NotFound();
            }

            return View(categoryFromDb);
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteTodo(int? id)
        {
            var obj = _db.TodoItems.Find(id);
            if (obj == null)
            {
                return NotFound();
            }

            _db.TodoItems.Remove(obj);
            _db.SaveChanges();
            TempData["success"] = "Task deleted successfully!";
            return RedirectToAction("Index");
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h2 class="display-4 mt-5">Welcome</h2>
    <h1 class="display-4">To Do Application</h1>
    <p>Application made as part of the Final thesis at the Faculty of Electrical Engineering, University of East Sarajevo.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - To Do App</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ToDoApplication_MVC.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><i class="bi bi-card-checklist"></i>&nbsp; To Do App</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TodoItem" asp-action="Index">Tasks</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; October 2022 - Vasilije Čabarkapa 1962
            <span class="float-end">Created in ASP.NET 6 Model View Controller</span>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_Notification.cshtml
@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]')
    </script>
}

@if (TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["error"]')
    </script>
}

Views/TodoItem/Create.cshtml
@model TodoItem
@{
    ViewData["Title"] = "Add new Task";
}

<form method="post">
    <div class="p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-dark">Add new Task</h2>
            <hr />
        </div>
        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Description"></label>
            <input asp-for="Description" class="form-control" />
            <span asp-validation-for="Description" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="DateAndTime"></label>
            <input asp-for="DateAndTime" class="form-control" />
            <span asp-validation-for="DateAndTime" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Priority"></label>
            <select asp-for="Priority" class="form-select" aria-label="Priority">
                <option value="" selected>Select a priority</option>
                <option value="High">High</option>
                <option value="Medium">Medium</option>
                <option value="Low">Low</option>
            </select>
            <span asp-validation-for="Priority" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <div class="form-check">
                <input class="form-check-input" type="checkbox" asp-for="isDone">
                <label class="form-check-label" asp-for="isDone"></label>
            </div>
        </div>
        <button type="submit" class="btn btn-dark" style="width:150px">
            Add
        </button>
        <a asp-controller="TodoItem" asp-action="Index" class="btn btn-danger" style="width:150px">
            Back to List
        </a>
    </div>
</form>

@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

Views/TodoItem/Delete.cshtml
@model TodoItem
@{
    ViewData["Title"] = "Delete Task";
}

<form method="post" asp-action="DeleteTodo">
    <input asp-for="Id" hidden />
    <div class="p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-dark">Are you sure you want to delete the task?</h2>
            <hr />
        </div>
        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" disabled class="form-control" />
        </div>
        <div class="mb-3">
            <label asp-for="Description"></label>
            <input asp-for="Description" disabled class="form-control" />
        </div>
        <div class="mb-3">
            <label asp-for="DateAndTime"></label>
            <input asp-for="DateAndTime" disabled class="form-control" />
        </div>
        <div class="mb-3">
            <label asp-for="Priority"></label>
            <select asp-for="Priority" disabled class="form-select" aria-label="Priority">
                <option value="" selected>Select a priority</option>
                <option value="High">High</option>
                <option value="Medium">Medium</option>
                <option value="Low">Low</option>
            </select>
        </div>
        <div class="mb-3">
            <div class="form-check">
                <input class="form-check-input" disabled type="checkbox" asp-for="isDone">
                <label class="form-check-label" asp-for="isDone"></label>
            </div>
        </div>
        <button type="submit" class="btn btn-dark" style="width:150px">
            Delete
        </button>
        <a asp-controller="TodoItem" asp-action="Index" class="btn btn-danger" style="width:150px">
            Back to List
        </a>
    </div>
</form>

@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

Views/TodoItem/Index.cshtml
@model IEnumerable<TodoItem>
@{
    ViewData["Title"] = "To Do List";
}

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-dark">To Do List</h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="TodoItem" asp-action="Create" class="btn btn-dark">
                <i class="bi bi-plus-circle"></i> &nbsp; Add new Task
            </a>
        </div>
    </div>
</div>
<br />
<div class="table-responsive">
    <table class="table table-bordered table-striped" width="100%">
    <thead>
        <tr>
            <th>
                Name
            </th>
            <th>
                Description
            </th>
            <th>
                Date
            </th>
            <th>
                Priority
            </th>
            <th>
                Done
            </th>
            <th>

            </th>
        </tr>
    </thead>
    <tbody>
        @foreach(var obj in Model)
        {
            <tr>
                <td width="20%">
                    @obj.Name
                </td>
                <td width="20%">
                    @obj.Description
                </td>
                <td width="20%">
                    @obj.DateAndTime
                </td>
                <td width="20%">
                    @obj.Priority
                </td>
                <td width="20%">
                    @if(@obj.isDone)
                    {
                        <i class="bi bi-check-lg"></i>
                    }
                    else
                    {
                        <i class="bi bi-x-lg"></i>
                    }
                </td>
                <td>
                    <div class="w-75 btn-group" role="group">
                        <a asp-controller="TodoItem" asp-action="Update" asp-route-id="@obj.Id" class="btn btn-dark rounded mx-2 text-center">
                            <i class="bi bi-pencil-square"></i> &nbsp; Edit
                        </a>
                        <a asp-controller="TodoItem" asp-action="Delete" asp-route-id="@obj.Id" class="btn btn-danger rounded mx-2 text-center">
                            <i class="bi bi-trash"></i> &nbsp; Delete
                        </a>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>
</div>

Views/TodoItem/Update.cshtml
@model TodoItem
@{
    ViewData["Title"] = "Edit Task";
}

<form method="post" asp-action="Update">
    <div class="p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-dark">Edit Task</h2>
            <hr />
        </div>
        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Description"></label>
            <input asp-for="Description" class="form-control" />
            <span asp-validation-for="Description" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="DateAndTime"></label>
            <input asp-for="DateAndTime" class="form-control" />
            <span asp-validation-for="DateAndTime" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Priority"></label>
            <select asp-for="Priority" class="form-select" aria-label="Priority">
                <option value="" selected>Select a priority</option>
                <option value="High">High</option>
                <option value="Medium">Medium</option>
                <option value="Low">Low</option>
            </select>
            <span asp-validation-for="Priority" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <div class="form-check">
                <input class="form-check-input" type="checkbox" asp-for="isDone">
                <label class="form-check-label" asp-for="isDone"></label>
            </div>
        </div>
        <button type="submit" class="btn btn-dark" style="width:150px">
            Edit
        </button>
        <a asp-controller="TodoItem" asp-action="Index" class="btn btn-danger" style="width:150px">
            Back to List
        </a>
    </div>
</form>

@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}